# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RunUMISampling <- function(data, sample_val, upsample = FALSE, display_progress = TRUE) {
    .Call('_BioData_RunUMISampling', PACKAGE = 'BioData', data, sample_val, upsample, display_progress)
}

RunUMISamplingPerCell <- function(data, sample_val, upsample = FALSE, display_progress = TRUE) {
    .Call('_BioData_RunUMISamplingPerCell', PACKAGE = 'BioData', data, sample_val, upsample, display_progress)
}

RowMergeMatrices <- function(mat1, mat2, mat1_rownames, mat2_rownames, all_rownames) {
    .Call('_BioData_RowMergeMatrices', PACKAGE = 'BioData', mat1, mat2, mat1_rownames, mat2_rownames, all_rownames)
}

LogNorm <- function(data, scale_factor, display_progress = TRUE) {
    .Call('_BioData_LogNorm', PACKAGE = 'BioData', data, scale_factor, display_progress)
}

FastMatMult <- function(m1, m2) {
    .Call('_BioData_FastMatMult', PACKAGE = 'BioData', m1, m2)
}

FastRowScale <- function(mat, scale = TRUE, center = TRUE, scale_max = 10, display_progress = TRUE) {
    .Call('_BioData_FastRowScale', PACKAGE = 'BioData', mat, scale, center, scale_max, display_progress)
}

Standardize <- function(mat, display_progress = TRUE) {
    .Call('_BioData_Standardize', PACKAGE = 'BioData', mat, display_progress)
}

FastSparseRowScale <- function(mat, scale = TRUE, center = TRUE, scale_max = 10, display_progress = TRUE) {
    .Call('_BioData_FastSparseRowScale', PACKAGE = 'BioData', mat, scale, center, scale_max, display_progress)
}

FastCov <- function(mat, center = TRUE) {
    .Call('_BioData_FastCov', PACKAGE = 'BioData', mat, center)
}

FastCovMats <- function(mat1, mat2, center = TRUE) {
    .Call('_BioData_FastCovMats', PACKAGE = 'BioData', mat1, mat2, center)
}

FastRBind <- function(mat1, mat2) {
    .Call('_BioData_FastRBind', PACKAGE = 'BioData', mat1, mat2)
}

FastExpMean <- function(mat, display_progress) {
    .Call('_BioData_FastExpMean', PACKAGE = 'BioData', mat, display_progress)
}

FastLogVMR <- function(mat, display_progress) {
    .Call('_BioData_FastLogVMR', PACKAGE = 'BioData', mat, display_progress)
}

ComputeSNN <- function(nn_ranked, prune) {
    .Call('_BioData_ComputeSNN', PACKAGE = 'BioData', nn_ranked, prune)
}

WriteEdgeFile <- function(snn, filename, display_progress) {
    invisible(.Call('_BioData_WriteEdgeFile', PACKAGE = 'BioData', snn, filename, display_progress))
}

DirectSNNToFile <- function(nn_ranked, prune, display_progress, filename) {
    .Call('_BioData_DirectSNNToFile', PACKAGE = 'BioData', nn_ranked, prune, display_progress, filename)
}

