# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ZScore <- function(data, display_progress = TRUE) {
    .Call('_BioData_ZScore', PACKAGE = 'BioData', data, display_progress)
}

